package org.jwellman.jcx;

import com.jidesoft.swing.FolderChooser;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.commons.lang.SystemUtils;

/**
 * A simple UI/Panel for the JCXEngine.
 *
 * @author Rick Wellman
 */
public class JCXConsole extends javax.swing.JPanel {

    private List<String> commands = new ArrayList<String>();

    /**
     * Creates new form JCXConsole
     */
    public JCXConsole() {
        initComponents();
        folderChooser.setAvailableButtons(
                FolderChooser.BUTTON_DESKTOP
              + FolderChooser.BUTTON_MY_DOCUMENTS
              + FolderChooser.BUTTON_REFRESH
              + FolderChooser.BUTTON_NEW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stdout = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        commandline = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        stderr = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        cmdExecute = new javax.swing.JButton();
        folderChooser = new com.jidesoft.swing.FolderChooser();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        stdout.setEditable(false);
        stdout.setBackground(new java.awt.Color(0, 0, 0));
        stdout.setColumns(60);
        stdout.setFont(new java.awt.Font("Monospaced", 0, 12));
        stdout.setForeground(new java.awt.Color(51, 255, 0));
        stdout.setRows(20);
        stdout.setText("stdout");
        jScrollPane2.setViewportView(stdout);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        commandline.setColumns(60);
        commandline.setRows(3);
        commandline.setTabSize(4);
        commandline.setText("command-line >");
        jScrollPane3.setViewportView(commandline);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.PAGE_END);

        stderr.setEditable(false);
        stderr.setBackground(new java.awt.Color(0, 0, 0));
        stderr.setColumns(60);
        stderr.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        stderr.setForeground(new java.awt.Color(255, 0, 51));
        stderr.setRows(5);
        stderr.setText("stderr");
        jScrollPane1.setViewportView(stderr);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setMinimumSize(new java.awt.Dimension(250, 121));
        jPanel2.setLayout(new java.awt.BorderLayout());

        cmdExecute.setText("Execute");
        cmdExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExecuteActionPerformed(evt);
            }
        });
        jPanel2.add(cmdExecute, java.awt.BorderLayout.NORTH);

        folderChooser.setControlButtonsAreShown(false);
        folderChooser.setNavigationFieldVisible(true);
        folderChooser.setRecentListVisible(false);
        folderChooser.setSelectedFolder(null);
        jPanel2.add(folderChooser, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExecuteActionPerformed
        this.stderr.setText("");
        this.stdout.setText("");

        commands.clear();
        if (SystemUtils.IS_OS_WINDOWS) { 
            commands.add("cmd.exe"); // need /windows/system32/ ?
            commands.add("/C");
        } else { // For now, assume Linux
            commands.add("/bin/bash"); // alias expansion requires export BASH_ENV=~/.bashrc *and* shopt -s expand_aliases
            commands.add("-c");
        }
        commands.add(commandline.getText());

        // execute the command
        SystemCommandExecutor ce = new SystemCommandExecutor(commands, stdout, stderr, folderChooser.getSelectedFolder());
        try {
            ce.executeCommand();
        } catch (IOException ex) {
            Logger.getLogger(JCXConsole.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(JCXConsole.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdExecuteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdExecute;
    private javax.swing.JTextArea commandline;
    private com.jidesoft.swing.FolderChooser folderChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea stderr;
    private javax.swing.JTextArea stdout;
    // End of variables declaration//GEN-END:variables
}
